export const FETCH_PRODUCTS_REQUEST = "FETCH_PRODUCTS_REQUEST";
export const FETCH_PRODUCT_SUCCESS = "FETCH_PRODUCT_SUCCESS";
export const FETCH_PRODUCT_FAILURE = "FETCH_PRODUCT_FAILURE";
export const SET_PRODUCTS = " SET_PRODUCTS";
export const SELECTED_PRODUCTS = "  SELECTED_PRODUCTS";
// export const   REMOVE_SELECTED_PRODUCTS: "REMOVE_SELECTED_PRODUCTS",
